name: ci-feature

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necesario para publicar en GHCR con GITHUB_TOKEN
      actions: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test (with coverage)
        run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Check for Dockerfile
        run: |
          if [ ! -f "Dockerfile" ]; then
            echo "Error: Dockerfile not found in repository root"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image (tag = commit SHA)
        run: |
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME_LOWER:${COMMIT_SHA} .
          docker push $IMAGE_NAME_LOWER:${COMMIT_SHA}
          echo "IMAGE_URI=$IMAGE_NAME_LOWER:${COMMIT_SHA}" >> $GITHUB_ENV

      - name: Publicar resumen
        if: always()
        run: |
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "### CI Feature Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: $COMMIT_SHA" >> $GITHUB_STEP_SUMMARY
          echo "- Imagen: $IMAGE_NAME_LOWER:${COMMIT_SHA}" >> $GITHUB_STEP_SUMMARY
